import Head from 'next/head'
import Feed from '../HPcomponents/Feed'
import React, { useContext } from "react"
import { AuthContext } from '../context/auth'
import {useRouter} from "next/router"



export default function Home() {
  const {user} = useContext(AuthContext)


  function Redirect() {
    const router = useRouter();
    router.push("/login")
    return null
  }
  return (
    <div>
      <Head>
        <title>Reels Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        user?.uid ? <Feed/> : <Redirect/>
      }
    </div>
  )
}
