import Head from 'next/head'
import Feed from '../HPcomponents/Feed'
import React from "react"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Reels Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Feed/>
      </body>
     
     
    </div>
  )
}
